### ISSUE TITLE
Kuvan lähettäminen/jakaminen Galleriasta

### ISSUE THREAD

**Issue by dogiex** [dogiex/MIUI-8.0-XML-FINNISH#6]
Kuvan lähettäminen/jakaminen Galleriasta pysäyttää gallerian.
Kuvan voi kuitenkin jakaa virheestä huolimatta.

java.lang.IllegalArgumentException: Unknown element format
	at java.text.MessageFormat.parseVariable(MessageFormat.java:975)
	at java.text.MessageFormat.applyPattern(MessageFormat.java:416)
	at java.text.MessageFormat.<init>(MessageFormat.java:360)
	at java.text.MessageFormat.<init>(MessageFormat.java:374)
	at java.text.MessageFormat.format(MessageFormat.java:731)
	at com.miui.gallery.ui.PhotoPageFragmentBase$ChoiceManagerBase$3.run(PhotoPageFragmentBase.java)
	at android.os.Handler.handleCallback(Handler.java)
	at android.os.Handler.dispatchMessage(Handler.java)
	at android.os.Looper.loop(Looper.java)
	at android.app.ActivityThread.main(ActivityThread.java)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)

[Kuva](https://dl2.pushbulletusercontent.com/Zlel3r0spFoPiSbmdyShZskQJb69A58s/Screenshot_2017-03-14-11-42-54-370_com.miui.bugreport.png)

**Comment by dogiex** [comment]
@ingbrzy can you help me solve the issue, please? I really don't know where to start. Haven't really practiced how to solve logcats.

**Comment by dogiex** [comment]
Gallery share image problem. Gallery crashes when trying to send image.

**Comment by dogiex** [comment]
Image can be shared regardless of the crash.

**Comment by dogiex** [comment]
03-29 19:01:47.661  1502  3977 W AppOps  : Bad call: specified package com.miui.gallery under uid 99910022 but it is really -1

03-29 19:01:47.661  1502  3977 W AppOps  : java.lang.RuntimeException: here

03-29 19:01:47.661  1502  3977 W AppOps  : 	at com.android.server.AppOpsService.getOpsRawLocked(AppOpsService.java)

03-29 19:01:47.661  1502  3977 W AppOps  : 	at com.android.server.AppOpsService.getOpsLocked(AppOpsService.java)

03-29 19:01:47.661  1502  3977 W AppOps  : 	at com.android.server.AppOpsService.noteOperationUnchecked(AppOpsService.java)

03-29 19:01:47.661  1502  3977 W AppOps  : 	at com.android.server.AppOpsService.noteOperation(AppOpsService.java)

03-29 19:01:47.661  1502  3977 W AppOps  : 	at com.android.server.AppOpsService$2.getMountMode(AppOpsService.java)

03-29 19:01:47.661  1502  3977 W AppOps  : 	at com.android.server.AppOpsService$2.hasExternalStorage(AppOpsService.java)

03-29 19:01:47.661  1502  3977 W AppOps  : 	at com.android.server.MountService$MountServiceInternalImpl.hasExternalStorage(MountService.java)

03-29 19:01:47.661  1502  3977 W AppOps  : 	at com.android.server.MountService.getVolumeList(MountService.java)

03-29 19:01:47.661  1502  3977 W AppOps  : 	at android.os.storage.IMountService$Stub.onTransact(IMountService.java)

03-29 19:01:47.661  1502  3977 W AppOps  : 	at android.os.Binder.execTransact(Binder.java)

**Comment by dogiex** [comment]
Korjattu versioon 7.4.6
