### ISSUE TITLE
Asetukset -> kehittäjäasetukset

### ISSUE THREAD

**Issue by Vihru** [dogiex/MIUI-8.0-XML-FINNISH#61]
laitteena mi pad 2, viimeisin stable.. kehittäjäasetuksiin mentäessä kaatuu. kysyin inbrzyltä nii käski kattoa Settings.apk arrays.xml..

**Comment by Vihru** [comment]
java.lang.ArrayIndexOutOfBoundsException: length=5; index=5
at com.android.settings.DevelopmentSettings.cS(DevelopmentSettings.java)
at com.android.settings.DevelopmentSettings.bO(DevelopmentSettings.java)
at com.android.settings.DevelopmentSettings.s(DevelopmentSettings.java)
at com.android.settings.DevelopmentSettings.onResume(DevelopmentSettings.java)
at android.app.Fragment.performResume(Fragment.java:2096)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:928)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
at android.app.BackStackRecord.run(BackStackRecord.java:840)
at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1454)
at android.app.FragmentManagerImpl$1.run(FragmentManager.java:447)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5275)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)

**Comment by dogiex** [comment]
Ja viimeisin stable on? 8.5.1.0?

**Comment by dogiex** [comment]
Ja enkun kielellä kehittäjäasetukset toimii normaalisti?

**Comment by Vihru** [comment]
viimeisin stable joo 8.5.1.0 ja julkastu 767.6MB Jun 18, 2017 | 05:22PM. kokeilen enkuks ku pääsen kotiin. suomeks ei toiminu ainakaa.

**Comment by dogiex** [comment]
Joo testaa aina englanniksi sen jälkeen ja jos sekin bugaa niin ei ole käännöksessä vika, mutta jos ilmenee vain suomenkielellä niin sitten käännöksessä vika. ;)

**Comment by Vihru** [comment]
No ingbrzy vaan meinas että on translation issue.. niin sillä ohjasin sulle.

ke 21. kesäkuuta 2017 klo 13.54 Dogiex <notifications@github.com> kirjoitti:

**Comment by dogiex** [comment]
Testaa ensin englanninkielellä ja jos ei silloin bugaa niin sitten ilmoita uusiksi tänne.

**Comment by Vihru** [comment]
Testasin enkuks, ei bugittanut.

**Comment by dogiex** [comment]
Ok kattelen Jussin jälkeen sitten. Testaappa tämän viikon weekly Mi6;lla toimiiko siinä.

**Comment by dogiex** [comment]
Ja jos toimii on ongelma jo korjattu.

**Comment by dogiex** [comment]
Testaappas kun kerkiät sillä Mi6:lla tota uusinta 7.6.22 weeklyä ja toimiiko siinä kehittäjäasetukset.

**Comment by Vihru** [comment]
toimii uudella weeklyllä laitteessa mi6:ssa.. eli siinä mieles tän saa varmaan kuitata..kumpa vielä toimis joskus mipad 2:ssakin niin sais ohitettua näytön lukituksen sieltä.

**Comment by dogiex** [comment]
Ok hyvä. Seuraavassa versiossa siis pitäisi toimia myös Mi Pad 2.
